service: products-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    PRODUCTS_TABLE: Products
    STOCKS_TABLE: Stocks
    SQS_URL:
      Ref: catalogItemsQueue
    SNS_ARN:
      Ref: ProductTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - "Fn::GetAtt": [Products, Arn]
            - "Fn::GetAtt": [Stocks, Arn]
        - Effect: Allow
          Action: "sqs:*"
          Resource:
            - Fn::GetAtt: [catalogItemsQueue, Arn]
        - Effect: Allow
          Action: "sns:*"
          Resource:
            Ref: ProductTopic

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn

resources:
  Resources:
    Products:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
    Stocks:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: product_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.STOCKS_TABLE}
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: products-queue
    ProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: products-sns-topic
    ProductTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: pavel.kusnecov@gmail.com
        TopicArn: 
          Ref: ProductTopic
    
